# Generated by Django 4.0.5 on 2022-06-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_rank',
            field=models.IntegerField(default=0, verbose_name='회원등급'),
        ),
    ]
